
export default constant = {
	GET_MILK_START: "GET_MILK_START",
	GET_MILK_SUCCESS:"GET_MILK_SUCCESS",
	GET_MILK_FAILURE:"GET_MILK_FAILURE",
	ADD_MILK_START:"ADD_MILK_START",
	ADD_MILK_SUCCESS:"ADD_MILK_SUCCESS",
	ADD_Milk_FAILURE:"ADD_Milk_FAILURE",
	GET_ANIMAL_START:"GET_ANIMAL_START",
	GET_ANIMAL_SUCCESS:"GET_ANIMAL_SUCCESS",
	GET_ANIMAL_FAILURE:"GET_ANIMAL_FAILURE",
	FILTER_MILK_DATA_START:"FILTER_MILK_DATA_START",
	FILTER_MILK_DATA_SUCCESS:"FILTER_MILK_DATA_SUCCESS",
	FILTER_MILK_DATA_FAILURE:"FILTER_MILK_DATA_FAILURE",
	DELETE_MILK_START:"DELETE_MILK__START",
	DELETE_MILK_SUCCESS:"DELETE_MILK_SUCCESS",
	DELETE_MILK_FAILURE:"DELETE_MILK_FAILURE",
	EDIT_MILK_START:"EDIT_MILK__START",
	EDIT_MILK_SUCCESS:"EDIT_MILK_SUCCESS",
	EDIT_MILK_FAILURE:"EDIT_MILK__FAILURE",
	EDIT_MILK_VISIBLE:"EDIT_MILK_VISIBLE",
	SELECT_ANIMAL_TAG_VISIBLE:"SELECT_ANIMAL_TAG_VISIBLE",
	GET_ANIMAL_TAG_START:"GET_ANIMAL_TAG_START",
	GET_ANIMAL_TAG_SUCCESS:"GET_ANIMAL_TAG_SUCCESS",
	GET_ANIMAL_TAG_FAILURE:"GET_ANIMAL_TAG_FAILURE",
	SELECT_ANIMAL_TAG_ITEM:"SELECT_ANIMAL_TAG_ITEM"

	

}