
export default constant = {
	GET_MILK_START: "GET_MILK_START",
	GET_MILK_SUCCESS:"GET_MILK_SUCCESS",
	GET_MILK_FAILURE:"GET_MILK_FAILURE",
	ADD_MILK_START:"ADD_MILK_START",
	ADD_MILK_SUCCESS:"ADD_MILK_SUCCESS",
	ADD_Milk_FAILURE:"ADD_Milk_FAILURE"
}